// <auto-generated />
using System;
using LaCanteraStock.AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaCanteraStock.Migrations
{
    [DbContext(typeof(BDContexto))]
    partial class BDContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaCanteraStock.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaID = 1,
                            Activo = true,
                            Descripcion = "Camisetas deportivas",
                            Nombre = "Camiseta"
                        },
                        new
                        {
                            CategoriaID = 2,
                            Activo = true,
                            Descripcion = "Shorts deportivos",
                            Nombre = "Short"
                        },
                        new
                        {
                            CategoriaID = 3,
                            Activo = true,
                            Descripcion = "Pantalones deportivos",
                            Nombre = "Pantalón"
                        },
                        new
                        {
                            CategoriaID = 4,
                            Activo = true,
                            Descripcion = "Casacas y abrigos",
                            Nombre = "Casaca"
                        });
                });

            modelBuilder.Entity("LaCanteraStock.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TipoDocumentoID")
                        .HasColumnType("tinyint");

                    b.HasKey("ClienteID");

                    b.HasIndex("TipoDocumentoID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("LaCanteraStock.Models.DetalleConfeccion", b =>
                {
                    b.Property<int>("DetalleConfeccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleConfeccionID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TallaID")
                        .HasColumnType("smallint");

                    b.Property<int>("TelaID")
                        .HasColumnType("int");

                    b.Property<byte>("TipoEstampadoID")
                        .HasColumnType("tinyint");

                    b.HasKey("DetalleConfeccionID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("TallaID");

                    b.HasIndex("TelaID");

                    b.HasIndex("TipoEstampadoID");

                    b.ToTable("DetallesConfeccion");
                });

            modelBuilder.Entity("LaCanteraStock.Models.DetallePedido", b =>
                {
                    b.Property<int>("DetallePedidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetallePedidoID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoID")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoTallaID")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("DetallePedidoID");

                    b.HasIndex("PedidoID");

                    b.HasIndex("ProductoTallaID");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("LaCanteraStock.Models.EstadoPedido", b =>
                {
                    b.Property<byte>("EstadoPedidoID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoPedidoID");

                    b.ToTable("EstadosPedido");
                });

            modelBuilder.Entity("LaCanteraStock.Models.MetodoPago", b =>
                {
                    b.Property<byte>("MetodoPagoID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetodoPagoID");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("LaCanteraStock.Models.ModalidadPedido", b =>
                {
                    b.Property<byte>("ModalidadID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModalidadID");

                    b.ToTable("ModalidadesPedido");
                });

            modelBuilder.Entity("LaCanteraStock.Models.MovimientoStock", b =>
                {
                    b.Property<int>("MovimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PedidoID")
                        .HasColumnType("int");

                    b.Property<int>("ProductoTallaID")
                        .HasColumnType("int");

                    b.Property<byte>("TipoMovimientoID")
                        .HasColumnType("tinyint");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("MovimientoID");

                    b.HasIndex("PedidoID");

                    b.HasIndex("ProductoTallaID");

                    b.HasIndex("TipoMovimientoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("LaCanteraStock.Models.Pago", b =>
                {
                    b.Property<int>("PagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoID"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<byte>("MetodoPagoID")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PedidoID")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TipoPagoID")
                        .HasColumnType("tinyint");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("PagoID");

                    b.HasIndex("MetodoPagoID");

                    b.HasIndex("PedidoID");

                    b.HasIndex("TipoPagoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("LaCanteraStock.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<byte>("EstadoPedidoID")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregaReal")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ModalidadID")
                        .HasColumnType("tinyint");

                    b.Property<string>("NumeroBoleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("PedidoID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EstadoPedidoID");

                    b.HasIndex("ModalidadID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("LaCanteraStock.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsConjunto")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProductoID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("LaCanteraStock.Models.ProductoTalla", b =>
                {
                    b.Property<int>("ProductoTallaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoTallaID"));

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<short>("TallaID")
                        .HasColumnType("smallint");

                    b.HasKey("ProductoTallaID");

                    b.HasIndex("ProductoID");

                    b.HasIndex("TallaID");

                    b.ToTable("ProductoTallas");
                });

            modelBuilder.Entity("LaCanteraStock.Models.Talla", b =>
                {
                    b.Property<short>("TallaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("TallaID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint");

                    b.HasKey("TallaID");

                    b.ToTable("Tallas");

                    b.HasData(
                        new
                        {
                            TallaID = (short)1,
                            Nombre = "S",
                            Orden = (byte)0
                        },
                        new
                        {
                            TallaID = (short)2,
                            Nombre = "M",
                            Orden = (byte)0
                        },
                        new
                        {
                            TallaID = (short)3,
                            Nombre = "L",
                            Orden = (byte)0
                        },
                        new
                        {
                            TallaID = (short)4,
                            Nombre = "XL",
                            Orden = (byte)0
                        },
                        new
                        {
                            TallaID = (short)5,
                            Nombre = "XXL",
                            Orden = (byte)0
                        });
                });

            modelBuilder.Entity("LaCanteraStock.Models.Tela", b =>
                {
                    b.Property<int>("TelaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TelaID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TelaID");

                    b.ToTable("Telas");

                    b.HasData(
                        new
                        {
                            TelaID = 1,
                            Activo = true,
                            Descripcion = "Suave y transpirable",
                            Nombre = "Algodón peinado"
                        },
                        new
                        {
                            TelaID = 2,
                            Activo = true,
                            Descripcion = "Secado rápido",
                            Nombre = "Poliéster Dry-Fit"
                        },
                        new
                        {
                            TelaID = 3,
                            Activo = true,
                            Descripcion = "Elástico y cómodo",
                            Nombre = "Jersey deportivo"
                        });
                });

            modelBuilder.Entity("LaCanteraStock.Models.TipoDocumento", b =>
                {
                    b.Property<byte>("TipoDocumentoID")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Longitud")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDocumentoID");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("LaCanteraStock.Models.TipoEstampado", b =>
                {
                    b.Property<byte>("TipoEstampadoID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoEstampadoID");

                    b.ToTable("TiposEstampado");

                    b.HasData(
                        new
                        {
                            TipoEstampadoID = (byte)1,
                            Nombre = "Sublimado"
                        },
                        new
                        {
                            TipoEstampadoID = (byte)2,
                            Nombre = "Serigrafía"
                        },
                        new
                        {
                            TipoEstampadoID = (byte)3,
                            Nombre = "Bordado"
                        },
                        new
                        {
                            TipoEstampadoID = (byte)4,
                            Nombre = "Vinil"
                        });
                });

            modelBuilder.Entity("LaCanteraStock.Models.TipoMovimiento", b =>
                {
                    b.Property<byte>("TipoMovimientoID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoMovimientoID");

                    b.ToTable("TiposMovimiento");
                });

            modelBuilder.Entity("LaCanteraStock.Models.TipoPago", b =>
                {
                    b.Property<byte>("TipoPagoID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoPagoID");

                    b.ToTable("TiposPago");
                });

            modelBuilder.Entity("LaCanteraStock.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LaCanteraStock.Models.Cliente", b =>
                {
                    b.HasOne("LaCanteraStock.Models.TipoDocumento", null)
                        .WithMany()
                        .HasForeignKey("TipoDocumentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaCanteraStock.Models.DetalleConfeccion", b =>
                {
                    b.HasOne("LaCanteraStock.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.Talla", "Talla")
                        .WithMany()
                        .HasForeignKey("TallaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.Tela", "Tela")
                        .WithMany()
                        .HasForeignKey("TelaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.TipoEstampado", "TipoEstampado")
                        .WithMany()
                        .HasForeignKey("TipoEstampadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Talla");

                    b.Navigation("Tela");

                    b.Navigation("TipoEstampado");
                });

            modelBuilder.Entity("LaCanteraStock.Models.DetallePedido", b =>
                {
                    b.HasOne("LaCanteraStock.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.ProductoTalla", null)
                        .WithMany()
                        .HasForeignKey("ProductoTallaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaCanteraStock.Models.MovimientoStock", b =>
                {
                    b.HasOne("LaCanteraStock.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoID");

                    b.HasOne("LaCanteraStock.Models.ProductoTalla", null)
                        .WithMany()
                        .HasForeignKey("ProductoTallaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.TipoMovimiento", null)
                        .WithMany()
                        .HasForeignKey("TipoMovimientoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaCanteraStock.Models.Pago", b =>
                {
                    b.HasOne("LaCanteraStock.Models.MetodoPago", null)
                        .WithMany()
                        .HasForeignKey("MetodoPagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.TipoPago", null)
                        .WithMany()
                        .HasForeignKey("TipoPagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaCanteraStock.Models.Pedido", b =>
                {
                    b.HasOne("LaCanteraStock.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.EstadoPedido", null)
                        .WithMany()
                        .HasForeignKey("EstadoPedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.ModalidadPedido", null)
                        .WithMany()
                        .HasForeignKey("ModalidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LaCanteraStock.Models.Producto", b =>
                {
                    b.HasOne("LaCanteraStock.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaCanteraStock.Models.ProductoTalla", b =>
                {
                    b.HasOne("LaCanteraStock.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaCanteraStock.Models.Talla", null)
                        .WithMany()
                        .HasForeignKey("TallaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
